<?php

/**
 * @file
 * Implements statistic pages hooks
 */
ini_set('memory_limit', '-1');
require_once(__DIR__ . '/includes/constants.inc');
require_once(__DIR__ . '/includes/model/model.inc');

/**
 * Implements hook_permission().
 */
function opigno_learning_locker_stats_app_permission() {
  return array(
    'access learning locker stats' => array(
      'title' => t('Access Learning Locker statistics'),
      'description' => t('Be able to view Learning Locker statistic pages.'),
    ),
  );
}

/**
 * Implements hook_menu_alter().
 */
function opigno_learning_locker_stats_app_menu_alter(&$items) {
  if (isset($items['admin/config/services/tincanapi'])) $items['admin/opigno/system/tincanapi']=$items['admin/config/services/tincanapi'];
}

/**
 * Implements hook_menu().
 */
function opigno_learning_locker_stats_app_menu() {
  $items['admin/opigno-statistics/learning-locker-statistics'] = array(
    'title' => 'Learning Locker stats',
    'description' => t('Learning Locker'),
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/opigno-statistics/learning-locker-statistics/dashboard'),
    'access arguments' => array('access learning locker stats'),
  );

  $items['admin/opigno-statistics/learning-locker-statistics/dashboard'] = array(
    'title' => 'Dashboard',
    'description' => t('Dashboard'),
    'page callback' => 'opigno_learning_locker_stats_dashboard_page',
    'access arguments' => array('access learning locker stats'),
    'file' => 'includes/dashboard/dashboard.pages.inc'
  );

  $items['admin/opigno-statistics/learning-locker-statistics/dashboard/total-number-of-page-view.json'] = array(
    'page callback' => 'opigno_learning_locker_stats_dashboard_total_number_of_page_view_json_page',
    'access arguments' => array('access learning locker stats'),
    'file' => 'includes/dashboard/dashboard.pages.inc'
  );

  $items['admin/opigno-statistics/learning-locker-statistics/course-content'] = array(
    'title' => 'Course content',
    'description' => t('Learning Locker course content statistics'),
    'page callback' => 'opigno_learning_locker_stats_course_content_page',
    'access arguments' => array('access learning locker stats'),
    'file' => 'includes/course_content/course_content.pages.inc'
  );

  $items['admin/opigno-statistics/learning-locker-statistics/quizzes'] = array(
    'title' => 'Quizzes',
    'description' => t('Learning Locker quizzes statistics'),
    'page callback' => 'opigno_learning_locker_stats_quizzes_page',
    'access arguments' => array('access learning locker stats'),
    'file' => 'includes/quizzes/quizzes.pages.inc'
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function opigno_learning_locker_stats_app_theme($existing, $type, $theme, $path) {
  return array(
    'opigno_learning_locker_stats_dashboard' => array('template' => 'templates/dashboard/dashboard'),

    'opigno_learning_locker_stats_dashboard_widget_total_number_of_page_view' => array('template' => 'templates/dashboard/widgets/total_number_of_page_view/total_number_of_page_view'),
    'opigno_learning_locker_stats_dashboard_widget_total_number_of_page_view_current_week_aggregate_day_json' => array(),
    'opigno_learning_locker_stats_dashboard_widget_total_number_of_page_view_current_month_aggregate_day_json' => array(),
    'opigno_learning_locker_stats_dashboard_widget_total_number_of_page_view_current_year_aggregate_day_json' => array(),
    'opigno_learning_locker_stats_dashboard_widget_total_number_of_page_view_current_year_aggregate_month_json' => array(),
    'opigno_learning_locker_stats_dashboard_widget_total_number_of_page_view_forever_aggregate_day_json' => array(),
    'opigno_learning_locker_stats_dashboard_widget_total_number_of_page_view_forever_aggregate_month_json' => array(),
    'opigno_learning_locker_stats_dashboard_widget_total_number_of_page_view_forever_aggregate_year_json' => array(),

    'opigno_learning_locker_stats_dashboard_widget_top_10_viewed_pages' => array('template' => 'templates/dashboard/widgets/top_10_viewed_pages/top_10_viewed_pages'),
    'opigno_learning_locker_stats_dashboard_widget_top_10_viewed_pages_list' => array('template' => 'templates/dashboard/widgets/top_10_viewed_pages/partials/list'),
    'opigno_learning_locker_stats_dashboard_widget_top_10_viewed_pages_list_item' => array('template' => 'templates/dashboard/widgets/top_10_viewed_pages/partials/list_item'),

    'opigno_learning_locker_stats_dashboard_widget_most_active_users' => array('template' => 'templates/dashboard/widgets/most_active_users/most_active_users'),
    'opigno_learning_locker_stats_dashboard_widget_most_active_users_list' => array('template' => 'templates/dashboard/widgets/most_active_users/partials/list'),
    'opigno_learning_locker_stats_dashboard_widget_most_active_users_list_item' => array('template' => 'templates/dashboard/widgets/most_active_users/partials/list_item'),

    'opigno_learning_locker_stats_dashboard_widget_last_statements' => array('template' => 'templates/dashboard/widgets/last_statements/last_statements'),

    'opigno_learning_locker_stats_course_content' => array('template' => 'templates/course_content/course_content'),
    'opigno_learning_locker_stats_course_content_general_statistics' => array('template' => 'templates/course_content/widgets/general_statistics/general_statistics'),
    'opigno_learning_locker_stats_course_content_course_contexts_statistics' => array('template' => 'templates/course_content/widgets/course_contexts_statistics/course_contexts_statistics'),
    'opigno_learning_locker_stats_course_content_widget_course_contexts_statistics_list' => array('template' => 'templates/course_content/widgets/course_contexts_statistics/partials/list'),
    'opigno_learning_locker_stats_course_content_widget_course_contexts_statistics_list_item' => array('template' => 'templates/course_content/widgets/course_contexts_statistics/partials/list_item'),

    'opigno_learning_locker_stats_quizzes' => array('template' => 'templates/quizzes/quizzes'),
    'opigno_learning_locker_stats_quizzes_list' => array('template' => 'templates/quizzes/partials/list'),
    'opigno_learning_locker_stats_quizzes_list_item' => array('template' => 'templates/quizzes/partials/list_item'),

    'opigno_learning_locker_stats_statements_list' => array('template' => 'templates/partials/statements/list'),
    'opigno_learning_locker_stats_statements_list_item' => array('template' => 'templates/partials/statements/list_item')
  );
}

/**
 * Implements hook_opigno_course_passed().
 *
 * @param int $course_nid
 * @param int $uid
 */
function opigno_learning_locker_stats_app_course_passed($course_nid, $uid) {
  global $base_url;
  $course = node_load($course_nid);
  $data = array(
    'verb' => tincanapi_get_verb('passed'),
    'object' => tincanapi_get_object('node', $course),
    'context' => array(
      'contextActivities' => array(
        'grouping' => array(
          array(
            'id' => $base_url . '/node/' . $course_nid,
            'definition' => array(
              'name' => array('en-US' => $course->title),
              'type' => TINCANAPI_CUSTOM_URI . '/content/type/' . $course->type
            ),
            'objectType' => 'Activity'
          )
        )
      )
    )
  );
  tincanapi_track_data('opigno_learning_locker_stats_app', $data, user_load($uid));
}